version: '3.8'

services:
  api:
    image: rodcordeiro/api:latest
    container_name: rod_api
    restart: always
    ports:
      - '3333:80'
    env_file:
      - .env
    networks:
      - rod

networks:
  rod:
    driver: bridge
